apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: {{ include "threatstack-agent.name" .}}
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" .}}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "threatstack-agent.name" .}}
subjects: 
- kind: ServiceAccount
  name: {{ include "threatstack-agent.name" .}}
  namespace: {{ .Release.Namespace }}