apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threatstack-agent.fullname" . }}
  namespace: {{ .Values.rbac.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" . }}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  ts-setup-args: "--deploy-key {{ .Values.agentDeployKey }} --ruleset '{{ .Values.rulesets }}' {{ .Values.additionalSetupConfig }}"
